### ISSUE TITLE
Can't expand `~` when running as service

### ISSUE THREAD

**Issue by jnevelson** [sethvargo/chef-api#47]
I ran into this issue when using this gem (version 0.7.0) to deregister a node from the chef server on shutdown.

I'm manually configuring the gem (`ChefAPI.configure { ... }`) rather than passing in a path to the config options, so I don't have an environment variable set for `CHEF_API_CONFIG`, which caused it to default to trying to expand `~`, which isn't defined when running as a service.

The bug happened on [this line](https://github.com/sethvargo/chef-api/blob/v0.7.0/lib/chef-api/defaults.rb#L27), and the full stack trace is:

```
/usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:27:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:27:in `config'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:48:in `endpoint'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:19:in `block in options'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:19:in `map'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/defaults.rb:19:in `options'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/configurable.rb:59:in `block in reset!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/configurable.rb:58:in `each'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api/configurable.rb:58:in `reset!'
    from /usr/local/lib/ruby/gems/2.1.0/gems/chef-api-0.7.0/lib/chef-api.rb:98:in `<top (required)>'
```

Happy to submit a PR to fix, but not sure what the best approach would be. For now I'm working around it by manually setting `ENV['CHEF_API_CONFIG']` to a non-existent path to short-circuit the bug.

Thanks!

**Comment by olleolleolle** [comment]
Hi! 

The issue that you report can be explained as "don't try to expand ~ when you know there's no `HOME` available:

Here is me, taking away the HOME env var:

```
irb(main):001:0> File.expand_path '~/.irbrc'
=> "/Users/olle/.irbrc"
irb(main):002:0> ENV.key?('HOME')
=> true
irb(main):003:0> ENV.delete('HOME')
=> "/Users/olle"
irb(main):004:0> ENV.key?('HOME')
=> false
irb(main):005:0> File.expand_path '~/.irbrc'
ArgumentError: couldn't find HOME environment -- expanding `~'
	from (irb):5:in `expand_path'
	from (irb):5
	from /Users/olle/.rubies/ruby-2.3.3/bin/irb:11:in `<top (required)>'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /Users/olle/.gem/ruby/2.3.3/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /Users/olle/.gem/ruby/2.3.3/bin/bundle:22:in `load'
	from /Users/olle/.gem/ruby/2.3.3/bin/bundle:22:in `<main>'
```
